apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lunch-app
  description: Lunch App
  annotations:
    github.com/project-slug: OrkoHunter/lunch-app
    backstage.io/techdocs-ref: dir:.
    rootly.com/app-name: lunch-app
    pagerduty.com/integration-key: 6f595b537c18400ec0b7f6d5ab302536
    grafana/tag-selector: lunch-app
    prometheus.io/rule: go_memstats_heap_idle_bytes
  links:
    - url: https://mars.com
      title: Rockit Lunch App
      icon: dashboard
spec:
  type: website
  lifecycle: experimental
  owner: travel-ex
  system: mars-mission
  dependsOn:
    - component:default/userdb
    - component:default/flight-info
  consumesApis:
    - flight-info
