apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lunch-app
  description: Lunch App
  annotations:
    github.com/project-slug: Rockit-Rockets/lunch-app
    backstage.io/techdocs-ref: dir:.
    rootly.com/app-name: lunch-app
    grafana/tag-selector: lunch-app
    prometheus.io/rule: go_memstats_heap_idle_bytes
    jenkins.io/github-folder: Rockit-Rockets/lunch-app
    apiVersion: backstage.io/v1alpha1
    vault.io/secrets-path: secret/rockit
  links:
    - url: https://mars.com
      title: Rockit Lunch App
      icon: dashboard
spec:
  type: website
  lifecycle: experimental
  owner: travel-ex
  system: mars-mission
  dependsOn:
    - component:default/userdb
    - component:default/flight-info
  consumesApis:
    - flight-info
